// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auuxixjweoolyegrbduh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1dXhpeGp3ZW9vbHllZ3JiZHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzIyMTIsImV4cCI6MjA1OTU0ODIxMn0.PacOfqqwMeONDxeHBRVyRsgNNdJt6bEXW9p6BDn7tlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);